# -*- coding: utf-8 -*-
"""ami _project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iNjzRvQ6mgwkTJsp38S7TA4VsHgIYwac

##Step 1 — Set Paths Correctly and load data from drive
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/VanshikaKumawat/podcast-transcription-segmentation.git
# %cd podcast-transcription-segmentation
!git status --porcelain

import os

DATASET_PATH = "/content/drive/MyDrive/ami/amicorpous"

print("FILES INSIDE amicorpus:\n")
for f in os.listdir(DATASET_PATH):
    print(f)

import os

TRANSCRIPT_PATH = "/content/drive/MyDrive/ami/manual_annotations"

print("FILES INSIDE manual_annotations:\n")
for f in os.listdir(TRANSCRIPT_PATH):
    print(f)

"""## Processed_transcript folder
### Merge and clean session transcripts A–D for audio alignment.
"""

import os
import xml.etree.ElementTree as ET
import re

TRANSCRIPT_PATH = "/content/drive/MyDrive/ami/manual_annotations"
OUTPUT_PATH = "/content/drive/MyDrive/ami/processed_transcripts"

os.makedirs(OUTPUT_PATH, exist_ok=True)

# Helper to clean session name from filename
def clean_session_name(filename):
    # Remove suffix like ".A.words.xml" and extra (1),(2)
    session = re.sub(r'\s*\(\d+\)', '', filename)  # remove (1),(2)
    session = session.split('.')[0]  # ES2002a
    return session

# Group transcripts by cleaned session
sessions = {}
for f in os.listdir(TRANSCRIPT_PATH):
    if f.endswith(".words.xml"):
        session = clean_session_name(f)
        sessions.setdefault(session, []).append(f)

# Parse XML and combine text per session
for session, files in sessions.items():
    combined_text = ""
    # Sort files by part (A, B, C, D)
    files_sorted = sorted(files, key=lambda x: re.search(r'\.([A-D])\.words\.xml', x).group(1))

    for file in files_sorted:
        tree = ET.parse(os.path.join(TRANSCRIPT_PATH, file))
        root = tree.getroot()
        for w in root.iter('w'):
            combined_text += (w.text or "") + " "

    combined_text = combined_text.strip()

    # Save combined transcript
    output_file = os.path.join(OUTPUT_PATH, f"{session}.txt")
    with open(output_file, 'w', encoding='utf-8') as f_out:
        f_out.write(combined_text)

    print(f"Processed {session} -> {output_file}")

"""## Step 2 — Load Audio + Normalize Volume"""

!pip install librosa soundfile noisereduce

import os
import librosa
import soundfile as sf
import numpy as np
import noisereduce as nr
from IPython.display import Audio, display

# Original audio folder
ORIGINAL_PATH = "/content/drive/MyDrive/ami/amicorpous"

# Folder to save cleaned audio
CLEANED_PATH = "/content/drive/MyDrive/ami/cleaned_audio"
os.makedirs(CLEANED_PATH, exist_ok=True)

audio_files = [f for f in os.listdir(ORIGINAL_PATH) if f.endswith(".wav")]
print("Audio files found:", audio_files)

for file in audio_files:
    path = os.path.join(ORIGINAL_PATH, file)

    # Load audio
    audio, sr = librosa.load(path, sr=16000)

    # Noise reduction
    audio_reduced = nr.reduce_noise(y=audio, sr=sr)

    # Normalize
    audio_normalized = librosa.util.normalize(audio_reduced)

    # Boost volume a bit (optional, +3 dB)
    audio_boosted = audio_normalized * 1.4
    audio_boosted = np.clip(audio_boosted, -1.0, 1.0)

    # Save cleaned audio
    out_path = os.path.join(CLEANED_PATH, file)
    sf.write(out_path, audio_boosted, sr)

    print("Processed & saved:", out_path)

# def play_audio_files(file_list, folder_path, label="Audio"):
#     for file in file_list:
#         print(f"Playing {label}: {file}")
#         display(Audio(os.path.join(folder_path, file)))

# print("=== ORIGINAL AUDIO ===")
# play_audio_files(audio_files, ORIGINAL_PATH, label="Original")

# print("=== CLEANED AUDIO ===")
# cleaned_files = [f for f in os.listdir(CLEANED_PATH) if f.endswith(".wav")]
# play_audio_files(cleaned_files, CLEANED_PATH, label="Cleaned")

"""## Step 3 — Run Whisper ASR"""

!pip install -q openai-whisper

import whisper
import os

# You can choose 'small', 'base', 'medium', 'large' depending on speed vs accuracy
model = whisper.load_model("base")

TRANSCRIPT_PATH = "/content/drive/MyDrive/ami/asr_transcripts"
os.makedirs(TRANSCRIPT_PATH, exist_ok=True)

# List all cleaned audio files
cleaned_files = [f for f in os.listdir(CLEANED_PATH) if f.endswith(".wav")]

for file in cleaned_files:
    audio_file = os.path.join(CLEANED_PATH, file)

    # Transcribe
    result = model.transcribe(audio_file, verbose=False)

    # Save plain text transcript
    txt_path = os.path.join(TRANSCRIPT_PATH, file.replace(".wav", ".txt"))
    with open(txt_path, "w") as f:
        f.write(result["text"])

    # Save segments with timestamps (start, end, text)
    segments_path = os.path.join(TRANSCRIPT_PATH, file.replace(".wav", "_segments.txt"))
    with open(segments_path, "w") as f:
        for segment in result["segments"]:
            start = segment["start"]
            end = segment["end"]
            text = segment["text"]
            f.write(f"{start:.2f}-{end:.2f} : {text}\n")

    print("Transcribed and saved:", txt_path)
    print("Segments saved with timestamps:", segments_path)

"""align the ASR transcripts with your AMI session names (ES2002a, ES2002b, …) and combine all parts A/B/C/D for each session into a single transcript, ready for segmentation."""

import os

# Cleaned audio transcripts
TRANSCRIPT_PATH = "/content/drive/MyDrive/ami/asr_transcripts"

# Folder to save final combined session transcripts
FINAL_TRANSCRIPT_PATH = "/content/drive/MyDrive/ami/final_session_transcripts"
os.makedirs(FINAL_TRANSCRIPT_PATH, exist_ok=True)

# Get all ASR transcript files
transcript_files = [f for f in os.listdir(TRANSCRIPT_PATH) if f.endswith(".txt") and not f.endswith("_segments.txt")]

print("Found transcripts:", transcript_files)

import re

def get_session_name(filename):
    """
    Extract session name from cleaned audio file/transcript.
    Example:
    'ES2002a.Mix-Lapel.wav' or 'ES2002a.A.words.txt' -> 'ES2002a'
    """
    match = re.match(r"(ES\d{4}[a-d])", filename)
    if match:
        return match.group(1)
    return None

from collections import defaultdict

# Dictionary to store transcripts per session
session_transcripts = defaultdict(list)

for file in transcript_files:
    session = get_session_name(file)
    if session:
        # Read transcript
        path = os.path.join(TRANSCRIPT_PATH, file)
        with open(path, "r") as f:
            text = f.read().strip()
        session_transcripts[session].append((file, text))

for session, parts in session_transcripts.items():
    # Sort by part letter if available (A/B/C/D)
    def part_key(filename_text_tuple):
        fname = filename_text_tuple[0]
        match = re.search(r"\.([A-D])", fname)
        return match.group(1) if match else "Z"

    sorted_parts = sorted(parts, key=part_key)

    # Combine all parts into one session transcript
    combined_text = "\n".join([text for fname, text in sorted_parts])

    # Save final session transcript
    out_file = os.path.join(FINAL_TRANSCRIPT_PATH, f"{session}.txt")
    with open(out_file, "w") as f:
        f.write(combined_text)

    print(f"Combined transcript saved for session {session} -> {out_file}")

"""Play your cleaned audio session by session.

Display the combined transcript for that session right below the audio player.

Quickly inspect ASR quality and identify errors for corrections.
"""

import os
from IPython.display import Audio, display
import textwrap

# Paths
CLEAN_AUDIO_PATH = "/content/drive/MyDrive/ami/cleaned_audio"
FINAL_TRANSCRIPT_PATH = "/content/drive/MyDrive/ami/final_session_transcripts"

# List all audio files
audio_files = [f for f in os.listdir(CLEAN_AUDIO_PATH) if f.endswith(".wav")]

# Loop through each session
for audio_file in audio_files:
    # Extract session name (e.g., ES2002a)
    session = audio_file.split(".")[0]

    # Find corresponding transcript
    transcript_file = f"{session}.txt"
    transcript_path = os.path.join(FINAL_TRANSCRIPT_PATH, transcript_file)

    print(f"\n===== SESSION: {session} =====\n")

    # Play audio
    audio_path = os.path.join(CLEAN_AUDIO_PATH, audio_file)
    display(Audio(audio_path, autoplay=False))

    # Display transcript in readable paragraph format
    if os.path.exists(transcript_path):
        with open(transcript_path, "r") as f:
            text = f.read()

        # Wrap text to 100 characters per line
        wrapped_text = textwrap.fill(text, width=100)
        print("Transcript:\n")
        print(wrapped_text)
    else:
        print("Transcript not found for this session.")

    # Pause before next session
    input("\nPress Enter to play next session...\n")

# Get all cleaned audio and transcripts
audio_files = sorted([f for f in os.listdir(CLEAN_AUDIO_PATH) if f.endswith(".wav")])
transcript_files = sorted([f for f in os.listdir(FINAL_TRANSCRIPT_PATH) if f.endswith(".txt")])

print("Audio sessions:", audio_files)
print("Transcript sessions:", transcript_files)

"""Merge manual transcripts in same A/B/C/D order"""

import os
import xml.etree.ElementTree as ET

MANUAL_PATH = "/content/drive/MyDrive/ami/manual_annotations"
MERGED_MANUAL_PATH = "/content/drive/MyDrive/ami/manual_merged"
os.makedirs(MERGED_MANUAL_PATH, exist_ok=True)

sessions = ["ES2002a", "ES2002b", "ES2002c", "ES2002d"]
parts = ["A", "B", "C", "D"]

def parse_manual_xml(file_path):
    """Extract words in file order (do NOT sort by timestamp)"""
    tree = ET.parse(file_path)
    root = tree.getroot()
    words = [w.text for w in root.findall(".//w") if w.text]
    return " ".join(words)

for session in sessions:
    merged_text = []
    for part in parts:
        filename = f"{session}.{part}.words.xml"
        file_path = os.path.join(MANUAL_PATH, filename)
        if os.path.exists(file_path):
            text = parse_manual_xml(file_path)
            merged_text.append(text)
        else:
            print(f"⚠️ Missing manual file: {filename}")

    final_text = "\n".join(merged_text)
    out_file = os.path.join(MERGED_MANUAL_PATH, f"{session}_manual.txt")
    with open(out_file, "w", encoding="utf-8") as f:
        f.write(final_text)
    print(f"✅ Merged manual transcript saved for session {session}")

import os

ASR_DIR = "/content/drive/MyDrive/ami/asr_transcripts"
sessions = ["ES2002a", "ES2002b", "ES2002c", "ES2002d"]

for session in sessions:
    print("\n" + "="*80)
    print(f"SESSION: {session}")
    print("="*80)

    whisper_file = f"{session}.Mix-Lapel.txt"
    whisper_path = os.path.join(ASR_DIR, whisper_file)

    if os.path.exists(whisper_path):
        print(f"✅ Found Whisper transcript: {whisper_file}")

        print("\n--- FILE PREVIEW ---\n")
        with open(whisper_path, "r", encoding="utf-8") as f:
            preview = f.read(500)
        print(preview)
    else:
        print(f"❌ Missing Whisper transcript: {whisper_file}")

import os
import xml.etree.ElementTree as ET

# ===============================
# PATHS (LOCK THESE)
# ===============================
BASE_PATH = "/content/drive/MyDrive/ami"
MANUAL_PATH = f"{BASE_PATH}/manual_annotations"
MANUAL_MERGED_PATH = f"{BASE_PATH}/manual_merged"

os.makedirs(MANUAL_MERGED_PATH, exist_ok=True)

sessions = ["ES2002a", "ES2002b", "ES2002c", "ES2002d"]

# ===============================
# MERGE FUNCTION
# ===============================
def merge_manual_session(session_id):
    words = []

    for speaker in ["A", "B", "C", "D"]:
        fname = f"{session_id}.{speaker}.words.xml"
        fpath = os.path.join(MANUAL_PATH, fname)

        if not os.path.exists(fpath):
            print(f"⚠️ Missing file: {fname}")
            continue

        tree = ET.parse(fpath)
        root = tree.getroot()

        for elem in root.iter():
            tag = elem.tag.split("}")[-1]

            if tag == "w" and elem.text:
                token = elem.text.strip()
                words.append(token)

    return " ".join(words)

# ===============================
# MERGE ALL SESSIONS
# ===============================
for session_id in sessions:
    manual_text = merge_manual_session(session_id)

    out_file = os.path.join(
        MANUAL_MERGED_PATH,
        f"{session_id}_manual.txt"
    )

    with open(out_file, "w") as f:
        f.write(manual_text)

    print(f"\n✅ {session_id} MANUAL TRANSCRIPT")
    print("Total words:", len(manual_text.split()))
    print("Saved to:", out_file)

import os
import textwrap

MANUAL_MERGED_PATH = "/content/drive/MyDrive/ami/manual_merged"

manual_files = sorted(
    [f for f in os.listdir(MANUAL_MERGED_PATH) if f.endswith("_manual.txt")]
)

for manual_file in manual_files:
    session = manual_file.replace("_manual.txt", "")

    print("\n" + "=" * 80)
    print(f"===== MANUAL TRANSCRIPT | SESSION: {session} =====")
    print("=" * 80 + "\n")

    manual_path = os.path.join(MANUAL_MERGED_PATH, manual_file)

    with open(manual_path, "r") as f:
        text = f.read()

    wrapped_text = textwrap.fill(text, width=100)

    print(wrapped_text)
    print("\nTotal words:", len(text.split()))

    input("\nPress Enter to view next manual transcript...\n")

"""## Step 4 — Compare With Ground-Truth Transcripts"""

!pip install jiwer

import os
import re
from jiwer import wer, cer, process_words

# Paths
MANUAL_MERGED_PATH = "/content/drive/MyDrive/ami/manual_merged"
FINAL_TRANSCRIPT_PATH = "/content/drive/MyDrive/ami/final_session_transcripts"

# List sessions
sessions = ["ES2002a", "ES2002b", "ES2002c", "ES2002d"]

# Function to normalize text for WER
def normalize_text(text):
    # lowercase
    text = text.lower()
    # remove punctuation
    text = re.sub(r"[^\w\s]", "", text)
    # remove extra whitespace
    text = re.sub(r"\s+", " ", text).strip()
    return text

# Compute WER for each session
for session in sessions:
    manual_file = os.path.join(MANUAL_MERGED_PATH, f"{session}_manual.txt")
    asr_file = os.path.join(FINAL_TRANSCRIPT_PATH, f"{session}.txt")

    if not os.path.exists(manual_file) or not os.path.exists(asr_file):
        print(f"⚠️ Missing manual or ASR transcript for {session}")
        continue

    with open(manual_file, "r") as f:
        manual_text = normalize_text(f.read())

    with open(asr_file, "r") as f:
        asr_text = normalize_text(f.read())

    # Compute WER
    session_wer = wer(manual_text, asr_text)
    session_cer = cer(manual_text, asr_text)

    print(f"\n===== SESSION: {session} =====")
    print(f"WER: {session_wer:.4f} ({session_wer*100:.2f}%)")
    print(f"CER: {session_cer:.4f} ({session_cer*100:.2f}%)")

from difflib import SequenceMatcher

def highlight_differences(ref, hyp):
    ref_words = ref.split()
    hyp_words = hyp.split()

    sm = SequenceMatcher(None, ref_words, hyp_words)
    diff_output = []

    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag == "equal":
            diff_output.extend(ref_words[i1:i2])
        elif tag == "replace":
            diff_output.extend([f"[{w}]" for w in hyp_words[j1:j2]])
        elif tag == "insert":
            diff_output.extend([f"[+{w}]" for w in hyp_words[j1:j2]])
        elif tag == "delete":
            diff_output.extend([f"[-{w}]" for w in ref_words[i1:i2]])

    return " ".join(diff_output)

# Show differences for all sessions
for session in sessions:
    manual_file = os.path.join(MANUAL_MERGED_PATH, f"{session}_manual.txt")
    asr_file = os.path.join(FINAL_TRANSCRIPT_PATH, f"{session}.txt")

    if not os.path.exists(manual_file) or not os.path.exists(asr_file):
        continue

    with open(manual_file, "r") as f:
        manual_text = normalize_text(f.read())

    with open(asr_file, "r") as f:
        asr_text = normalize_text(f.read())

    diff_text = highlight_differences(manual_text, asr_text)

    print("\n" + "="*80)
    print(f"===== WORD-LEVEL DIFFERENCES | SESSION: {session} =====")
    print("="*80 + "\n")
    print(diff_text[:2000])  # print first 2000 chars
    print("\n[...truncated...]")
    input("\nPress Enter to view next session differences...\n")

import os

# -------------------------
# Paths
# -------------------------
BASE_PATH = "/content/drive/MyDrive/ami"
MANUAL_PATH = f"{BASE_PATH}/manual_annotations"
MANUAL_MERGED_PATH = f"{BASE_PATH}/manual_merged"
FINAL_TRANSCRIPT_PATH = f"{BASE_PATH}/final_session_transcripts"
OUTPUT_CSV = f"{BASE_PATH}/manual_vs_asr_comparison.csv"

os.makedirs(MANUAL_MERGED_PATH, exist_ok=True)

sessions = ["ES2002a", "ES2002b", "ES2002c", "ES2002d"]
speakers = ["A", "B", "C", "D"]

# Quick check of folder contents
print("Manual files:", os.listdir(MANUAL_PATH)[:10])
print("Final ASR files:", os.listdir(FINAL_TRANSCRIPT_PATH)[:10])

import xml.etree.ElementTree as ET

def merge_manual_session(session_id):
    words = []
    for speaker in speakers:
        fname = f"{session_id}.{speaker}.words.xml"
        fpath = os.path.join(MANUAL_PATH, fname)
        if not os.path.exists(fpath):
            print(f"⚠️ Missing manual file: {fname}")
            continue

        tree = ET.parse(fpath)
        root = tree.getroot()
        for elem in root:
            tag = elem.tag.split("}")[-1]
            if tag == "w" and elem.text:
                words.append(elem.text.strip())

    return " ".join(words)

# Merge all sessions
for session_id in sessions:
    manual_text = merge_manual_session(session_id)
    out_file = os.path.join(MANUAL_MERGED_PATH, f"{session_id}_manual.txt")
    with open(out_file, "w") as f:
        f.write(manual_text)
    print(f"✅ {session_id} merged. Total words: {len(manual_text.split())}, saved to: {out_file}")

import textwrap

for manual_file in sorted(os.listdir(MANUAL_MERGED_PATH)):
    if not manual_file.endswith("_manual.txt"):
        continue

    session = manual_file.replace("_manual.txt", "")
    manual_path = os.path.join(MANUAL_MERGED_PATH, manual_file)

    if os.path.exists(manual_path):
        with open(manual_path, "r") as f:
            text = f.read()
        print("\n" + "="*80)
        print(f"SESSION: {session}, Words: {len(text.split())}")
        print(textwrap.fill(text[:1000], width=100))  # preview first 1000 chars
    else:
        print(f"⚠️ Manual transcript missing for {session}")

import os
from jiwer import wer
import re

# Paths
MERGED_MANUAL_PATH = "/content/drive/MyDrive/ami/manual_merged/"
FINAL_TRANSCRIPT_PATH = "/content/drive/MyDrive/ami/processed_transcripts/"

# Function to normalize ASR text (light normalization)
def normalize_asr_text(text):
    text = text.lower()
    text = re.sub(r'\s+', ' ', text).strip()
    return text

# Get manual files and ASR files
manual_files = [f for f in os.listdir(MERGED_MANUAL_PATH) if f.endswith(".txt")]
asr_files = [f for f in os.listdir(FINAL_TRANSCRIPT_PATH) if f.endswith(".txt")]

accuracy_results = {}

for manual_file in manual_files:
    session_id = manual_file.split("_manual")[0]  # Extract session like ES2002a
    manual_path = os.path.join(MERGED_MANUAL_PATH, manual_file)

    # Find corresponding ASR file
    matching_asr = [f for f in asr_files if f.startswith(session_id)]
    if matching_asr:
        asr_path = os.path.join(FINAL_TRANSCRIPT_PATH, matching_asr[0])

        # Read texts
        with open(manual_path, "r", encoding="utf-8") as f:
            manual_text = f.read()  # Keep manual text as-is

        with open(asr_path, "r", encoding="utf-8") as f:
            asr_text = normalize_asr_text(f.read())  # Light normalization for ASR

        # Compute WER and accuracy
        error = wer(manual_text, asr_text)
        accuracy = 1 - error
        accuracy_results[session_id] = (accuracy, error)
    else:
        accuracy_results[session_id] = (None, None)

# Print results
for session, values in accuracy_results.items():
    accuracy, error = values
    if accuracy is not None:
        print(f"{session} Accuracy: {accuracy*100:.2f}% | WER: {error*100:.2f}%")
    else:
        print(f"{session} Accuracy: ASR file missing")

import os
from jiwer import wer
import re

# Paths
MERGED_MANUAL_PATH = "/content/drive/MyDrive/ami/manual_merged/"
FINAL_TRANSCRIPT_PATH = "/content/drive/MyDrive/ami/processed_transcripts/"

# Function to normalize text
def normalize_text(text):
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)  # remove punctuation
    fillers = ['um', 'uh', 'mm-hmm', 'ah', 'oh', 'yeah', 'okay']
    for f in fillers:
        text = re.sub(r'\b' + f + r'\b', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

# Get manual files and ASR files
manual_files = [f for f in os.listdir(MERGED_MANUAL_PATH) if f.endswith(".txt")]
asr_files = [f for f in os.listdir(FINAL_TRANSCRIPT_PATH) if f.endswith(".txt")]

accuracy_results = {}

# Iterate over manual files
for manual_file in manual_files:
    session_id = manual_file.split("_manual")[0]  # Extract session like ES2002a
    manual_path = os.path.join(MERGED_MANUAL_PATH, manual_file)

    # Find corresponding ASR file
    matching_asr = [f for f in asr_files if f.startswith(session_id)]
    if matching_asr:
        asr_path = os.path.join(FINAL_TRANSCRIPT_PATH, matching_asr[0])

        # Read and normalize
        manual_text = normalize_text(open(manual_path, "r", encoding="utf-8").read())
        asr_text = normalize_text(open(asr_path, "r", encoding="utf-8").read())

        # Compute accuracy
        error = wer(manual_text, asr_text)
        accuracy_results[session_id] = 1 - error
    else:
        accuracy_results[session_id] = None

# Print results
for session, acc in accuracy_results.items():
    if acc is not None:
        print(f"{session} Accuracy: {acc*100:.2f}%")
    else:
        print(f"{session} Accuracy: ASR file missing")

"""# Topic Segmentation"""

import os
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import sent_tokenize

# ----------------- Existing preprocessing & keyword extraction -----------------

def preprocess_for_topics(text):
    import re
    text = text.lower()
    text = re.sub(r"\b(uh|um|erm|ah|mm|hmm)\b", "", text)
    text = re.sub(r"[^a-z0-9\.\s]", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

def add_paragraph_breaks(text, sentences_per_paragraph=6):
    sentences = sent_tokenize(text)
    paragraphs = []
    for i in range(0, len(sentences), sentences_per_paragraph):
        para = " ".join(sentences[i:i+sentences_per_paragraph])
        paragraphs.append(para)
    return "\n\n".join(paragraphs)

def extract_keywords_tfidf(text, top_k=8):
    vectorizer = TfidfVectorizer(
        stop_words="english",
        max_df=1.0,
        min_df=1
    )
    tfidf = vectorizer.fit_transform([text])
    scores = tfidf.toarray()[0]
    terms = vectorizer.get_feature_names_out()
    ranked = sorted(zip(terms, scores), key=lambda x: x[1], reverse=True)
    keywords = [term for term, score in ranked[:top_k]]
    return keywords

# ----------------- New: Segment + keywords + summaries -----------------

def summarize_segment(segment_text, keywords, max_sentences=3):
    """
    Simple extractive summary:
    - Rank sentences by the number of keyword matches.
    - Pick top N sentences for the summary.
    """
    sentences = sent_tokenize(segment_text)
    ranked = []
    for s in sentences:
        score = sum(s.lower().count(k) for k in keywords)
        ranked.append((score, s))
    # Sort descending by score
    ranked.sort(reverse=True)
    # Take top N sentences
    summary_sentences = [s for score, s in ranked[:max_sentences]]
    return " ".join(summary_sentences)

def segment_and_extract_keywords_and_summarize(session_file, sentences_per_segment=6, top_k=8, print_preview=True):
    # Read transcript
    with open(session_file, "r", encoding="utf-8") as f:
        text = f.read()

    # Preprocess text
    clean_text = preprocess_for_topics(text)

    # Add paragraph breaks (TextTiling style)
    paragraph_text = add_paragraph_breaks(clean_text, sentences_per_paragraph=sentences_per_segment)
    segments = paragraph_text.split("\n\n")

    session_results = []
    for i, seg in enumerate(segments, 1):
        keywords = extract_keywords_tfidf(seg, top_k=top_k)
        summary = summarize_segment(seg, keywords)
        session_results.append({
            "segment_number": i,
            "text": seg,
            "keywords": keywords,
            "summary": summary
        })
        if print_preview:
            print(f"\n--- Segment {i} ---")
            print(f"Text: {seg[:300]}...")
            print(f"Keywords: {keywords}")
            print(f"Summary: {summary}\n")

    return session_results

# ----------------- Example usage for all sessions -----------------

FINAL_TRANSCRIPT_PATH = "/content/drive/MyDrive/ami/final_session_transcripts"
sessions = ["ES2002a", "ES2002b", "ES2002c", "ES2002d"]

all_sessions_results = {}
for session in sessions:
    session_file = os.path.join(FINAL_TRANSCRIPT_PATH, f"{session}.txt")
    print(f"\n==================== SESSION: {session} ====================")
    all_sessions_results[session] = segment_and_extract_keywords_and_summarize(session_file)

"""transformer-based summaries (like BART/T5)"""

# ----------------- Keyword / phrase search across segments -----------------

def search_keyword_summary(all_sessions_results, keyword, speaker=None):
    """
    Search all sessions for a keyword and return the summaries of relevant segments.

    Parameters:
    - all_sessions_results: dict of session -> segments info
    - keyword: str, word/phrase to search
    - speaker: str or None, if you want to filter by speaker (requires transcripts with speaker tags)

    Returns:
    - dict of session -> list of matched segments with summaries
    """
    keyword = keyword.lower()
    results = {}

    for session, segments in all_sessions_results.items():
        matched_segments = []
        for seg in segments:
            seg_text = seg['text'].lower()
            if keyword in seg_text:
                # Optional speaker filter
                if speaker:
                    if speaker.lower() not in seg_text:
                        continue
                matched_segments.append({
                    "segment_number": seg["segment_number"],
                    "keywords": seg["keywords"],
                    "summary": seg["summary"],
                    "text": seg["text"]
                })
        if matched_segments:
            results[session] = matched_segments

    return results

# ----------------- Example Usage -----------------
search_word = "project"  # keyword the user wants
search_speaker = None    # or "laura" / "david" etc.

matched_results = search_keyword_summary(all_sessions_results, search_word, speaker=search_speaker)

# Print nicely
for session, segments in matched_results.items():
    print(f"\n=== SESSION: {session} ===")
    for seg in segments:
        print(f"\nSegment {seg['segment_number']}")
        print(f"Keywords: {seg['keywords']}")
        print(f"Summary: {seg['summary']}")
        print(f"Text Preview: {seg['text'][:200]}...")  # first 200 chars

"""# UI part"""



